### ISSUE TITLE
First time layout invokes loadmore

### ISSUE THREAD

**Issue by zuoshu** [cymcsg/UltimateRecyclerView#124]
RecyclerView will invoke onScrolled(dx=0,dy=0) on the first layout, and then invoke onLoadMoreListener.loadMore if there is only 1 item in the list

**Comment by cymcsg** [comment]
There is a variable called ``showLoadMoreItemNum``.Do you think that can meets your requirement?

**Comment by chungchi300** [comment]
@cymcsg 

I have read the source code,but I don't understand why it is 
 if (mAdapter.getAdapterItemCount() >= showLoadMoreItemNum && mAdapter.getCustomLoadMoreView().getVisibility() == View.GONE) {
            mAdapter.getCustomLoadMoreView().setVisibility(View.VISIBLE);
        }
        if (mAdapter.getAdapterItemCount() < showLoadMoreItemNum) {
            mAdapter.getCustomLoadMoreView().setVisibility(View.GONE);
        }

For example,I have a search result that have 60,and the number of item per page is 6,what number should  I set?Because I will set it to 60.Sorry to ask such a beginner question

**Comment by chungchi300** [comment]
@zuoshu 
 I think what @cymcsg you can set your minShowLoadMoreViewNum to your itemPerPage(e.g 6) so that if you only have 1 item in the page,loadMoreViewNum will be hidden.

I see how it works,the showLoadMoreItemNum is a naming that is just not good enough,I will said it is minShowLoadMoreViewNum .

**Comment by jjhesk** [comment]
did you make any fork from this suggestion @chungchi300 ?

**Comment by jjhesk** [comment]
#276 this should be done for the load more issue. @chungchi300 @zuoshu @cymcsg
