### ISSUE TITLE
Wrong getPosition

### ISSUE THREAD

**Issue by smhgit** [cymcsg/UltimateRecyclerView#164]
Hi,

I've tried to use ultimate recycler view with different object types. I think that there is an issue with the method getPosition.

Maybe it should be changed from 

if (binderPosition <= 0) {

to

if (binderPosition < 0) {

As binder position 0 & 1 gets the same adpater position 0.

Thx

public int getPosition(DataBinder binder, int binderPosition) {
        E targetViewType = getEnumFromBinder(binder);
        for (int i = 0; i < getItemCount(); i++) {
            if (targetViewType == getEnumFromPosition(i)) {
                binderPosition--;
                if (binderPosition <= 0) {
                    return i;
                }
            }
        }
        return getItemCount();
    }

**Comment by smhgit** [comment]
Have anyone encounter this issue?

**Comment by Chenng** [comment]
Position 0 should not return 0?

**Comment by rotemitz** [comment]
I encountered the same issue,

I have 3 date binders and my list is divided to 3 sections. lets say i have letters, numbers and special chars as types and my data set looks something like this: 
[@, 1, 2, 3, a, b, c]

now i want to remove the 'b' item by calling notifyBinderItemRemoved(1) because 1 is the position of the 'b' item in the [a, b, c] letters section subset. 
until i=3, the binder position is still 1 and the loop keeps going, but for i=4, when we get to 'a' in the general data set, binderPosition becomes 0 which causes the method to return i=4.
if we look at the original data set, [@, 1, 2, 3, a, b, c] we can see that in position for lays the 'a' item and not the 'b' item which we just updated.

am i missing something?
