### ISSUE TITLE
what is the difference between FOOTER and CHANGED_FOOTER?

### ISSUE THREAD

**Issue by OVERSKY2003** [cymcsg/UltimateRecyclerView#278]
我看到设置disableLoadmore()后，会将 isLoadMoreChanged = true，然后就得到VIEW_TYPES.CHANGED_FOOTER。 FOOTER和CHANGED_FOOTER有什么区别？

我调用disableLoadmore()后，LoadMoreView不会消失，要调用notifyDataSetChanged才会消失，是要这样吗？

protected class VIEW_TYPES {
        public static final int NORMAL = 0;
        public static final int HEADER = 1;
        public static final int FOOTER = 2;
        public static final int CHANGED_FOOTER = 3;
    }

**Comment by jjhesk** [comment]
the code is a bit redundant. i think we should ignore CHANGED_FOOTER because it is used for internal use only. From the source mentioned CHANGED_FOOTER is the internal adjustment in [HERE](https://github.com/cymcsg/UltimateRecyclerView/blob/master/UltimateRecyclerView/ultimaterecyclerview/src/main/java/com/marshalchen/ultimaterecyclerview/UltimateViewAdapter.java#L93-L109)

**Comment by OVERSKY2003** [comment]
我调用disableLoadmore()后，LoadMoreView不会自动消失，要调用notifyDataSetChanged才会消失，是要这样吗？

**Comment by OVERSKY2003** [comment]
采用UltimateDifferentViewTypeAdapter，就没有自定义header和recyclerviewEmptyView了，对吗？

**Comment by jjhesk** [comment]
now i have done some works for the upgrades. =) 

[check here at](https://github.com/cymcsg/UltimateRecyclerView/blob/core-recode-redesign/UltimateRecyclerView/ultimaterecyclerview/src/main/java/com/marshalchen/ultimaterecyclerview/UltimateGridLayoutAdapter.java) #280

**Comment by jjhesk** [comment]
please now read #276
